// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsfBDYfVbFXUJIiAszy4AZTKMek_ePEaY',
    appId: '1:723179285746:web:197f9834816ed9b339f46b',
    messagingSenderId: '723179285746',
    projectId: 'nasa-52901',
    authDomain: 'nasa-52901.firebaseapp.com',
    storageBucket: 'nasa-52901.appspot.com',
    measurementId: 'G-FM39W2TVMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB59BO9fM8N06BLkAjez-dm9LEd4fKG-tI',
    appId: '1:723179285746:android:a50e7f8e75d5732639f46b',
    messagingSenderId: '723179285746',
    projectId: 'nasa-52901',
    storageBucket: 'nasa-52901.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3CtiC1BoG4AaU77iqYWT8zRGFWCiA-cA',
    appId: '1:723179285746:ios:cb4345b7590d153039f46b',
    messagingSenderId: '723179285746',
    projectId: 'nasa-52901',
    storageBucket: 'nasa-52901.appspot.com',
    iosBundleId: 'com.NASASpaceAppsChallenge.nasaSpaceSppsChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3CtiC1BoG4AaU77iqYWT8zRGFWCiA-cA',
    appId: '1:723179285746:ios:f66f4cdb5432b43d39f46b',
    messagingSenderId: '723179285746',
    projectId: 'nasa-52901',
    storageBucket: 'nasa-52901.appspot.com',
    iosBundleId: 'com.NASASpaceAppsChallenge.nasaSpaceSppsChallenge.RunnerTests',
  );
}
